services:
  - type: web
    name: vir
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vir-db
          property: connectionString

databases:
  - name: vir-db
