"""add realizado

Revision ID: 19196d2e6f9f
Revises: 
Create Date: 2025-04-20 14:33:42.827216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19196d2e6f9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrenamientos')
    op.drop_table('atletas')
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('entrenamiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realizado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenamiento', schema=None) as batch_op:
        batch_op.drop_column('realizado')

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    op.create_table('atletas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('atletas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('altura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('test_1000', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pr_10k', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pr_21k', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pr_42k', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='atletas_pkey'),
    sa.UniqueConstraint('email', name='atletas_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('entrenamientos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dia', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('detalle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], name='entrenamientos_atleta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entrenamientos_pkey')
    )
    # ### end Alembic commands ###
